#Route 1
image bg room = "images/bg room.png"
image bg room_2 = "images/bg room 2.png"
image bg intersection day = "images/bg street day.png"
image bg intersection evening = "images/bg street evening.png"
image bg gamecenter = "images/bg arcade.png"
image bg konbini = "images/bg konbini.png"
image bg famres = "images/bg restaurant.png"
image bg cinema = "images/bg shopping.png"
image bg shop = "images/bg shopping.png"
image bg park = "images/bg playground.png"

#Route 2
image bg forest = "images/r2_maps/r2_forest/forest.png"
image bg map = "images/r2_maps/r2_world_map/world_map.png"
image bg village = "images/r2_maps/r2_village/village.png"
image bg turmoil_front = "images/bg turmoil front.png"
image bg turmoil = "images/r2_maps/r2_turmoil/turmoil.png"
image bg rage = "images/bg rage front.png"
image bg tranquility_front = "images/bg tranquility front.png"
image bg tranquility = "images/r2_maps/r2_tranquility/tranquility.png"
image bg castle room = "images/r2_maps/castle.png"

#Route 3
image bg hub = "images/hub.png"
image bg quiz = "images/quiz room.png"
image bg sing = "images/sing room.png"
image bg river = "images/river bank.png"
image bg computer = "images/quiz room.png"
image bg secret_field = "images/bg r3 field.png"
image bg secret_sky = "images/bg r3 sky.png"
image bg secret_pudding = "images/bg r3 pudding.png"

#Miscellaneous
image black = "#000"

#Art Reel
image art_1 = "images/r3_art_reel/art_1.png"
image art_2 = "images/r3_art_reel/art_2.png"
image art_3 = "images/r3_art_reel/art_3.png"
image art_4 = "images/r3_art_reel/art_4.png"
image art_5 = "images/r3_art_reel/art_5.png"
image art_6 = "images/r3_art_reel/art_6.png"
image art_7 = "images/r3_art_reel/art_7.png"
image art_8 = "images/r3_art_reel/art_8.png"
image art_9 = "images/r3_art_reel/art_9.png"
image art_10 = "images/r3_art_reel/art_10.png"
image art_11 = "images/r3_art_reel/art_11.png"
image art_12 = "images/r3_art_reel/art_12.png"
image art_13 = "images/r3_art_reel/art_13.png"
image art_14 = "images/r3_art_reel/art_14.png"
image art_15 = "images/r3_art_reel/art_15.png"
image art_16 = "images/r3_art_reel/art_16.png"
image art_17 = "images/r3_art_reel/art_17.png"
image art_18 = "images/r3_art_reel/art_18.png"
image art_19 = "images/r3_art_reel/art_19.png"
image art_20 = "images/r3_art_reel/art_20.png"
