#List of Characters will be defined here
default player_name = _('Hitona')
default player_full_name = _('Hitona Kohigashi')
default player_last_name = _('Kohigashi')
define p = Character("tl_paren(player_name)", dynamic=True, color="#880088") #Player a.k.a KohigashiActual
default sn_name = _('Senpai')
define sn = Character("tl_paren(sn_name)", dynamic=True, color="#880000")
default s_name = _('Shiraishi')
define s = Character("tl_paren(s_name)", dynamic=True, color="#338833", image="hitona1") #KohiLO
default e_name = _('Eve')
define e = Character("tl_paren(e_name)", dynamic=True, color="#338833") #KohiC2
default so_name = _('Soldier')
define so = Character("tl_paren(so_name)", dynamic=True, color="#FF0000")
default hn_name = _('Hitoni')
define hn = Character("tl_paren(hn_name)", dynamic=True, color="#FF0000")
default hs_name = _('Hitoshi')
define hs = Character("tl_paren(hs_name)", dynamic=True, color="#FF0000")
default hj_name = _('Hitoju')
define hj = Character("tl_paren(hj_name)", dynamic=True, color="#FF0000")
default om_name = _('Old Man')
define om = Character("tl_paren(om_name)", dynamic=True, color="#FF0000")
default k_name = _('King')
define k = Character("tl_paren(k_name)", dynamic=True, color="#FF0000")
default pi_name = _('Pierrot')
define pi = Character("tl_paren(pi_name)", dynamic=True, color="#880088") #KohiSh
default l_name = _('Lios')
define l = Character("tl_paren(l_name)", dynamic=True, color="#FF0000")
default c_name = _('Cat')
define c = Character("tl_paren(c_name)", dynamic=True, color="#FF0000")
default do_name = _('Dog')
define do = Character("tl_paren(do_name)", dynamic=True, color="#FF0000")
default de_name = _('Deer')
define de = Character("tl_paren(de_name)", dynamic=True, color="#FF0000")
default r_name = _('Rabbit')
define r = Character("tl_paren(r_name)", dynamic=True, color="#000")

default everyone_name = _('Everyone')
define everyone = Character("tl_paren(everyone_name)", dynamic=True)
default waitress_name = _('Waitress')
define waitress = Character("tl_paren(waitress_name)", dynamic=True)
default mailman_name = _('Mailman')
define mailman = Character("tl_paren(mailman_name)", dynamic=True)
default friend_name = _('Friend')
define friend = Character("tl_paren(friend_name)", dynamic=True)
default cathy_name = _('Cathy')
define cathy = Character("tl_paren(cathy_name)", dynamic=True)
default captain_name = _('Captain')
define captain = Character("tl_paren(captain_name)", dynamic=True, color='#FF0000')
define l_and_pi = Character('{color=[l.who_args[color]]}[l!t]{/color} & {color=[pi.who_args[color]]}[pi!t]{/color}')
define p_and_pi = Character('{color=[p.who_args[color]]}[p!t]{/color} & {color=[pi.who_args[color]]}[pi!t]{/color}')
define p_and_s = Character('{color=[p.who_args[color]]}[p!t]{/color} & {color=[s.who_args[color]]}[s!t]{/color}')
define p_and_e = Character('{color=[p.who_args[color]]}[p!t]{/color} & {color=[e.who_args[color]]}[e!t]{/color}')
define l_and_p = Character('{color=[l.who_args[color]]}[l!t]{/color} & {color=[p.who_args[color]]}[p!t]{/color}')
