define audio.alarm = "audio/alarm_placeholder.wav"
define audio.doorbell = "audio/sfx/door_bell.mp3"
define audio.phonecall = "audio/sfx/phone_call.mp3"
define audio.dooropen = "audio/sfx/door_open.mp3"
define audio.challengecomplete = "audio/sfx/challenge_complete.mp3"
define audio.correctchoice = "audio/sfx/correct_choice.mp3"
define audio.cranegame = "audio/sfx/crane_game_get.mp3"
define audio.falsechoice_long = "audio/sfx/false_choice_long.mp3"
define audio.falsechoice_short = "audio/sfx/false_choice_short.mp3"
define audio.lightswitch = "audio/sfx/lights_off_on.mp3"
define audio.messagetone = "audio/sfx/message_tone.mp3"
define audio.quizquestion = "audio/sfx/quiz_question.mp3"
define audio.quizstart = "audio/sfx/quiz_start.mp3"
define audio.riverbank = "audio/sfx/river_bank.mp3"
define audio.takecard = "audio/sfx/take_card.mp3"
define audio.bombexplode = "audio/sfx/bomb_explode.mp3"

define audio.room_bgm = "audio/Route_1_-_Track_1_Sample.ogg"

define audio.adventure_bgm = "audio/Route_2_-_Adventure.ogg"
define audio.r2bad_bgm = "audio/Route_2_-_Bad_End.mp3"
define audio.battletheme_bgm = "audio/Route_2_-_Battle_Theme.mp3"
define audio.beforefinal_intro_bgm = "audio/Route_2_-_Before_Final_intro.ogg"
define audio.beforefinal_loop_bgm = "audio/Route_2_-_Before_Final_loop.ogg"
define audio.king_intro_bgm = "audio/Route_2_-_King_intro.ogg"
define audio.king_loop_bgm = "audio/Route_2_-_King_loop.ogg"
define audio.r2end_bgm = "audio/Route_2_-_End_Theme.mp3"

define audio.lios_bgm = "audio/Route_3_-_Track_1.mp3"
define audio.bomb_intro_bgm = "audio/Route_3_-_Track_2.ogg"
define audio.bomb_loop_bgm = "audio/Route_3_-_Track_3.ogg"
define audio.r3end_bgm = "audio/Route_3_-_End_Theme.mp3"
